development:
  adapter: mysql2
  database: captains_cake_ruby
  pool: 2
  username: root
  port: 11001
  host: 127.0.0.1
test:
  adapter: mysql2
  database: captains_cake_ruby_test
  pool: 2
  username: root
  port: 11001
  host: 127.0.0.1