strainNames = [
  "Blue Dream",
  "Sour Diesel",
  "GSC",
  "Green Crack",
  "OG Kush",
  "Granddaddy",
  "Purple",
  "Original Glue",
  "White Widow",
  "Blue Dream",
  "Sour Diesel",
  "GSC",
  "Green Crack",
  "OG Kush",
  "Granddaddy",
  "Purple",
  "Original Glue",
  "White Widow",
  "Jack Herer",
  "Bubba Kush",
  "Pineapple",
  "Express",
  "Trainwreck",
  "AK-47",
  "Durban Poison",
  "Northern Lights",
  "Headband",
  "Blue Cheese",
  "Strawberry Cough",
  "Chemdog",
  "Purple Kush",
  "Lemon Haze",
  "Super Lemon Haze",
  "Grape Ape",
  "Blueberry",
  "Alaskan Thunder",
  "Fuck",
  "Super Silver",
  "Haze",
  "Blackberry Kush",
  "Cherry Pie",
  "Master Kush",
  "Mazar x",
  "Blueberry OG",
  "Cheese",
  "Death Star",
  "Chocolope",
  "Amnesia Haze",
  "Tahoe OG Kush",
  "Maui Wowie",
  "Platinum GSC",
  "Harlequin",
  "Sherbert",
  "God's Gift",
  "LA Confidential",
  "Agent Orange",
  "Purple Urkle",
  "Lemon Kush",
  "Mazar x",
  "Blueberry",
  "Golden Goat",
  "Afghan Kush",
  "Dutch Treat",
  "Hindu Kush",
  "White Rhino",
  "Fire OG",
  "Tangie",
  "G13",
  "Mango Kush",
  "Berry White",
  "LSD",
  "Candyland",
  "Purple Haze",
  "Cinex",
  "Bruce Banner",
  "Lemon Skunk",
  "Bubble Gum",
  "Banana Kush",
  "Cinderella 99",
  "Jillybean",
  "Ghost Train Haze",
  "Blueberry Kush",
  "NYC Diesel",
  "Animal Cookies",
  "Kosher Kush",
  "Skunk",
  "Island Sweet",
  "XJ-13",
  "Alien OG",
  "Kush",
  "Cotton Candy",
  "Tangerine Dream",
  "FPOG",
  "Mr. Nice",
  "Lamb's Bread",
  "White Fire OG",
  "Romulan",
  "Cannatonic",
  "Critical Mass",
  "Chernobyl",
  "Holy Grail Kush",
  "Orange Kush",
  "Lavender",
  "Platinum OG",
  "Larry OG",
  "Silver Haze",
  "Thin Mint GSC",
  "9 Pound Hammer",
  "Sour OG",
  "Obama Kush",
  "Gelato",
  "Afgoo",
  "King Louis XIII",
  "ACDC",
  "Platinum Kush",
  "Juicy Fruit",
  "Sour Kush",
  "Critical Kush",
  "Amnesia",
  "Sensi Star",
  "Trainwreck",
  "Purple",
  "Pineapple Kush",
  "MK Ultra",
  "J1",
  "Flo",
  "God Bud",
  "Sweet Tooth",
  "Sister Glue",
  "Moby Dick",
  "Pink Kush",
  "Space Queen",
  "Blackberry",
  "Blue Diesel",
  "UK Cheese",
  "SFV OG",
  "Kandy Kush",
  "White Russian",
  "Super Skunk",
  "Acapulco Gold",
  "Blackwater",
  "Purple Diesel",
  "Khalifa Kush",
  "Lemon Diesel",
  "Pineapple",
  "Grapefruit",
  "Snowcap",
  "Kush",
  "Pre-98 Bubba",
  "Vanilla Kush",
  "Afghani",
  "Ghost OG",
  "Stardawg",
  "Herijuana",
  "Sour Tangie",
  "Orange Crush",
  "Deadhead OG",
  "Jack Frost",
  "Dr. Who",
  "Diesel",
  "Super Sour",
  "Casey Jones",
  "Mango",
  "Skunk No. 1",
  "Hash Plant",
  "Shark",
  "Great White",
  "Haze",
  "Jack the Ripper",
  "Cream",
  "Cookies and",
  "True OG",
  "Grape God",
  "$100 OG",
  "Banana",
  "Strawberry",
  "Golden Pineapple",
  "Blue Widow",
  "Permafrost",
  "Strawberry Kush",
  "Lemon OG Kush",
  "Blue Magoo",
  "Afgooey",
  "The White",
  "Grape Stomper",
  "Kush",
  "Platinum Bubba",
  "OG #18",
  "Banana OG",
  "Jesus OG",
  "Raspberry Kush",
  "Do-Si-Dos",
  "Chemdog 4",
  "Presidential OG",
  "Soda",
  "Black Cherry",
  "Snoop's Dream",
  "Diamond OG",
  "Purple OG Kush",
  "King's Kush",
  "Black Jack",
  "Headband",
  "Blueberry",
  "Pennywise",
  "Red Dragon",
  "707 Headband",
  "Power Plant",
  "Double Dream",
  "Ogre",
  "Cherry Kush",
  "Jedi Kush",
  "Kryptonite",
  "Orange",
  "California",
  "Blue Cookies",
  "3 Kings",
  "Bubblegum Kush",
  "Blueberry Diesel",
  "Ace of Spades",
  "Plushberry",
  "Black Widow",
  "Jack Flash",
  "Pure Kush",
  "Death Bubba",
  "Shishkaberry",
  "Dream Queen",
  "Kali Mist",
  "Blueberry Haze",
  "Rockstar",
  "Yoda OG",
  "Harle-Tsu",
  "Big Bud",
  "Jet Fuel",
  "Bruce Banner #3",
  "Pineapple Chunk",
  "Black Domina",
  "Bubba OG",
  "SAGE",
  "Cat Piss",
  "Violator Kush",
  "Diesel",
  "Strawberry",
  "Liberty Haze",
  "Dark Star",
  "Cheese",
  "Big Buddha",
  "Mendocino Purps",
  "Cheese Quake",
  "Jean Guy",
  "Black Diamond",
  "Nebula",
  "Blue Haze",
  "Pure Power Plant",
  "Charlotte's Web",
  "Diablo",
  "Paris OG",
  "Blueberry",
  "DJ Short",
  "Querkle",
  "XXX OG",
  "Mendo Breath",
  "Diesel",
  "Purple Sour",
  "Sour Tsunami",
  "Purple Dream",
  "Orange Bud",
  "Blue Dragon",
  "JGR",
  "Willy's Wonder",
  "Super Blue Dream",
  "Candy Jack",
  "Purple Candy",
  "Vortex",
  "Incredible",
  "Fucking",
  "Monster Cookies",
  "Orange Cookies",
  "Mob Boss",
  "Ice",
  "Chemo",
  "Cherry AK-47",
  "Quantum Kush",
  "Cookies Kush",
  "Key Lime Pie",
  "Cali Kush",
  "Tangerine Kush",
  "Sage N Sour",
  "Cheesecake",
  "Blueberry",
  "Cannalope Haze",
  "Glass Slipper",
  "Phantom Cookies",
  "Dogwalker OG",
  "Laughing Buddha",
  "Mango Haze",
  "Star Killer",
  "Trainwreck",
  "Pineapple",
  "Redwood Kush",
  "THC Bomb",
  "Chiesel",
  "Green Queen",
  "Tangerine",
  "Sugar Black Rose",
  "Tangerine Haze",
  "Kush",
  "Birthday Cake",
  "Sugar Cookie",
  "Shark Shock",
  "Death Star OG",
  "Bio-Diesel",
  "Superglue",
  "Hawaiian Snow",
  "Crack",
  "God's Green",
  "Diesel",
  "East Coast Sour",
  "Sour Apple",
  "Cataract Kush",
  "Thunder Fuck",
  "Matanuska",
  "Dairy Queen",
  "AK-48",
  "Alien Dawg",
  "Lemon G",
  "Chocolate Chunk",
  "M-39",
  "Head Cheese",
  "Superman OG",
  "Purple Wreck",
  "G13 Haze",
  "SFV OG Kush",
  "Chemdog 91",
  "Super Jack",
  "Blue Hawaiian",
  "Godfather OG",
  "Trinity",
  "Sour Grape",
  "Grapefruit Kush",
  "Chronic",
  "Red Congolese",
  "Alien Walker",
  "Royal Kush",
  "Kushberry",
  "Pitbull",
  "White Berry",
  "Nuken",
  "Allen Wrench",
  "Green Ribbon",
  "Lemon Drop",
  "Goo",
  "Critical Plus",
  "Black Tuna",
  "Zkittlez",
  "Pot of Gold",
  "Master Yoda",
  "Green Dream",
  "Sour Jack",
  "#5",
  "Northern Lights",
  "Dirty Girl",
  "Kush",
  "Purple Hindu",
  "Burmese Kush",
  "Qrazy Train",
  "Hell's OG",
  "Cherry Bomb",
  "Goji OG",
  "Clementine",
  "Tutankhamon",
  "Papaya",
  "Panama Red",
  "Charlie Sheen",
  "Strawberry",
  "Bubbleberry",
  "Darth Vader OG",
  "Jupiter OG",
  "Kosher Tangie",
  "Mars OG",
  "Alien Rock Candy",
  "Champagne Kush",
  "Cannalope Kush",
  "Timewreck",
  "Watermelon",
  "Grape Kush",
  "Critical Jack",
  "Orange Haze",
  "Blue Mystic",
  "24k Gold",
  "Blue OG",
  "Canna-Tsu",
  "Lemonade",
  "Strawberry",
  "Scooby Snacks",
  "Abusive OG",
  "Huckleberry",
  "Purple Mr. Nice",
  "Snow White",
  "Hawaiian",
  "Marionberry Kush",
  "Wonder Woman",
  "Cookie Monster",
  "Chocolope Kush",
  "Tangilope",
  "Grape Krush",
  "Black Mamba",
  "Apollo 13",
  "Cheese",
  "Confidential",
  "Cadillac Purple",
  "Ice Cream",
  "Ingrid",
  "Blue Crack",
  "Kimbo Kush",
  "Pandora's Box",
  "Exodus Cheese",
  "Dutch Hawaiian",
  "Purple Dragon",
  "King Kong",
  "Venom OG",
  "Fortune Cookies",
  "Snoop Dogg OG",
  "A-10",
  "Blue God",
  "Middlefork",
  "Conspiracy Kush",
  "Diesel",
  "Grapefruit",
  "Willie Nelson",
  "Maui",
  "Alien Kush",
  "Berries",
  "Mother of",
  "Buddha's Sister",
  "Medicine Man",
  "Hempstar",
  "Wedding Cake",
  "Cheesecake",
  "Strawberry",
  "Lemon Thai",
  "Green Candy",
  "OG Chem",
  "Somango",
  "UW",
  "Kong",
  "Purple Alien OG",
  "OG Shark",
  "3X Crazy",
  "Blue Rhino",
  "Purple Gorilla",
  "Euforia",
  "Thai",
  "Papa's OG",
  "MediHaze",
  "New Glue",
  "Cherry OG",
  "Afwreck",
  "Killer Queen",
  "Purple Punch",
  "Rare Darkness",
  "Lucky Charms",
  "Mazar I Sharif",
  "Lavender Jones",
  "Mother’s Helper",
  "The Hog",
  "Colombian Gold",
  "Bullrider",
  "Afghani",
  "Citrus Sap",
  "Kilimanjaro",
  "Lemon Jack",
  "Sour Cheese",
  "Kush",
  "Platinum Purple",
  "Phantom OG",
  "Church OG",
  "Purple Chemdawg",
  "Green Poison",
  "Lodi Dodi",
  "Rug Burn OG",
  "Banana",
  "Double Tangie",
  "Hippie Crippler",
  "Raskal OG",
  "Mickey Kush",
  "Blue Diamond",
  "Stranger",
  "Red Headed",
  "Power Kush",
  "Sour Dream",
  "Golden Ticket",
  "Cornbread",
  "Purple Elephant",
  "Scott's OG",
  "Hindu Skunk",
  "Corleone Kush",
  "Tora Bora",
  "Blue Goo",
  "Strawberry Haze",
  "Arjan's",
  "Lights",
  "Atomic Northern",
  "Purple Arrow",
  "Gorilla",
  "Silverback",
  "Crystal Coma",
  "Game Changer",
  "Remedy",
  "Rainbow",
  "White Nightmare",
  "Master Bubba",
  "Love Potion #1",
  "Moonshine Haze",
  "OG",
  "White Fire Alien",
  "Medibud",
  "Hog's Breath",
  "Blue Frost",
  "Primus",
  "OG Diesel Kush",
  "Hashberry",
  "Wonderland",
  "Alice in",
  "Sour Alien",
  "Silvertip",
  "Montana",
  "Cherry Diesel",
  "Pineapple Jack",
  "Blue Moon Rocks",
  "White Kush",
  "Silver Kush",
  "White Buffalo",
  "Sugar Shack",
  "Hawaiian Haze",
  "Dream",
  "Cinderella's",
  "Bay 11",
  "Alpha Blue",
  "LA Woman",
  "Recon",
  "Cure",
  "CBD Critical",
  "Dutch Dragon",
  "Neville's Haze",
  "Jack Skellington",
  "Honey Bananas",
  "Godberry",
  "Chocolate Thai",
  "Wappa",
  "Special Reserve",
  "Black Lime",
  "Yum",
  "Blueberry Yum",
  "Bay Dream",
  "Crack",
  "Super Green",
  "Purple Afghani",
  "Super Snow Dog",
  "501st OG",
  "Diesel",
  "Chemdawg Sour",
  "Triangle Kush",
  "Black Cherry OG",
  "Dynamite",
  "Sour Amnesia",
  "Cream Caramel",
  "Blue Knight",
  "Platinum Wreck",
  "Green Goblin",
  "C4",
  "Midnight",
  "Blue Moonshine",
  "Galactic Jack",
  "Balls",
  "Purple Monkey",
  "White Gold",
  "Cookie Wreck",
  "Blueberry Muffin",
  "Shipwreck",
  "Cracker Jack",
  "Sherbet",
  "Sour Banana",
  "Blue Kush",
  "Star",
  "Critical Sensi",
  "Fields",
  "Strawberry",
  "Grease Monkey",
  "Shiva Skunk",
  "Sweet Cheese",
  "Sour Cream",
  "Tangerine Power",
  "Chem Valley Kush",
  "Blueberry Skunk",
  "The Truth",
  "Sharksbreath",
  "White Lightning",
  "Aurora Indica",
  "Ringo's Gift",
  "Oregon Diesel",
  "Jah Kush",
  "Donna OG",
  "Purple Voodoo",
  "Face Off OG",
  "Dutchberry",
  "Deep Purple",
  "Purple Skunk",
  "Ambrosia",
  "Super Kush",
  "Shoreline",
  "Space Bomb",
  "Dragon's Breath",
  "Alaskan Ice",
  "Purple Berry",
  "Raspberry Cough",
  "Lucid Dream",
  "Cactus",
  "Santa Maria",
  "Night Terror OG",
  "Fruity",
  "Heavy Duty",
  "OG Cheese",
  "Sour Lemon OG",
  "CBD Shark",
  "Space Candy",
  "Northern Wreck",
  "Black Betty",
  "Ripped Bubba",
  "Pineapple Diesel",
  "Buddha Tahoe",
  "Sweet Diesel",
  "Banana Diesel",
  "Jamaican Dream",
  "Green Goddess",
  "Pineapple Thai",
  "A-Train",
  "Tutti Frutti",
  "Master Jedi",
  "Pink Panther",
  "Master OG",
  "303 OG",
  "Citrix",
]